name: Coverage to GitHub pages

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  coverage-build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [2.7, 3.9]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - run: |
          pip install coverage
      - run: |
          coverage run python.py
          coverage report
          mv .coverage .coverage.${{ matrix.python-version }}

      - uses: actions/upload-artifact@v2
        with:
          path: .coverage.${{ matrix.python-version }}

  coverage-report:
    needs: coverage-build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - run: |
          # Set $PATH for pip binaries https://github.com/actions/virtual-environments/issues/2455
          # Note that actions/setup-python@v2 does this automatically
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          pip install coverage
      - run: |
          ls -la artifact
          python -m coverage combine artifact/
          python -m coverage report
          python -m coverage html -d public_html
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public_html
